# Generated by Django 6.1.1 on 2026-09-09 10:21

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='picture',
            field=models.ImageField(upload_to=accounts.validators.avatar_upload_path),
        ),
    ]
